{% set name = "MolVS" %}
{% set version = "0.1.1" %}
{% set sha256 = "3679713d95774f69625e42b7e83b161be48df8d994768ba2786440f085497474" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - six
  run:
    - python
    - rdkit
    - six

test:
  imports:
    - molvs

about:
  home: https://github.com/mcs07/MolVS
  license: MIT
  license_file: LICENSE
  summary: 'Molecule Validation and Standardization'
  doc_url: https://molvs.readthedocs.io
  dev_url: https://github.com/mcs07/MolVS
