#!/usr/bin/env bash
set -x

# Remove homebrew.
echo ""
echo "Removing homebrew from Travis CI to avoid conflicts."
curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
chmod +x ~/uninstall_homebrew
~/uninstall_homebrew -fq
rm ~/uninstall_homebrew

# Install Miniconda.
echo ""
echo "Installing a fresh version of Miniconda."
curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > ~/miniconda.sh
bash ~/miniconda.sh -b -p ~/miniconda
source ~/miniconda/bin/activate root

# Configure conda.
echo ""
echo "Configuring conda."
conda config --add channels conda-forge
conda config --add channels mcs07
conda config --set show_channel_urls true
conda install --yes --quiet conda conda-forge-ci-setup=2.* conda-forge-pinning networkx conda-build>=3.16
source run_conda_forge_build_setup

# We just want to build all of the recipes.
python .ci_support/build_all.py ./recipes
