diff --git a/src/Makefile.in b/src/Makefile.in
index bf4181f..a86bc34 100644
--- a/src/Makefile.in
+++ b/src/Makefile.in
@@ -89,7 +89,7 @@ $(PROGRAM): $(LIBOBJS) gocr.o
 	$(CC) -o $@ $(LDFLAGS) gocr.o $(LIBOBJS) $(LIBS)
 	# if test -r $(PROGRAM); then cp $@ ../bin; fi
 
-libs: lib$(PGMASCLIB).a lib$(PGMASCLIB).@PACKAGE_VERSION@.so
+libs: lib$(PGMASCLIB).a
 
 #lib$(PGMASCLIB).@PACKAGE_VERSION@.so: $(LIBOBJS)
 #	$(CC) -fPIC -shared -Wl,-h$@ -o $@ $(LIBOBJS)
@@ -115,8 +115,6 @@ install: all
 	$(INSTALL) ../bin/gocr.tcl   $(DESTDIR)$(bindir)  # better X11/bin?
 	if test -f lib$(PGMASCLIB).a; then\
 	 $(INSTALL) lib$(PGMASCLIB).a $(DESTDIR)$(libdir);\
-	 $(INSTALL) lib$(PGMASCLIB).@PACKAGE_VERSION@.so $(DESTDIR)$(libdir);\
-	 $(INSTALL) lib$(PGMASCLIB).so $(DESTDIR)$(libdir);\
 	fi
 	# ToDo: not sure that the link will be installed correctly
 	#$(INSTALL) $(INCLUDEFILES) $(DESTDIR)$(includedir)
@@ -126,8 +124,6 @@ uninstall:
 	-rm -f $(DESTDIR)$(bindir)/$(PROGRAM)
 	-rm -f $(DESTDIR)$(bindir)/gocr.tcl
 	-rm -f $(DESTDIR)$(libdir)/lib$(PGMASCLIB).a
-	-rm -f $(DESTDIR)$(libdir)/lib$(PGMASCLIB).@PACKAGE_VERSION@.so
-	-rm -f $(DESTDIR)$(libdir)/lib$(PGMASCLIB).so
 	# ToDo: set to old version.so ?
 	#for X in $(INCLUDEFILES); do rm -f $(DESTDIR)$(includedir)/$$X; done
 
