{% set name = "osra" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/osra/files/osra/{{ version }}/{{ name }}-{{ version }}.tgz
  sha256: d32d38cfdfb70c153b0debe6ea69730c535a422d6a32fbe84508a464b979c138

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - gocr
    - graphicsmagick
    - ocrad
    - openbabel
    - poppler
    - potrace
    - tclap
  run:
    - gocr
    - graphicsmagick
    - ocrad
    - openbabel
    - poppler
    - potrace


test:
  commands:
    - osra --help

about:
  home: https://sourceforge.net/projects/osra/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'Convert images of chemical structures into computer recognizable formats'
  description: |
    OSRA is a utility designed to convert graphical representations of chemical structures and 
    reactions, as they appear in journal articles, patent documents, textbooks, trade magazines 
    etc., into SMILES or SD file format- a computer recognizable molecular structure.
  doc_url: https://sourceforge.net/p/osra/wiki/Home/
  dev_url: https://sourceforge.net/projects/osra/

extra:
  recipe-maintainers:
    - mcs07
