#!/usr/bin/env bash


# Set the numpy variable. This isn't used, but conda-build complains if we haven't set it already.
export CONDA_NPY=19

# Remove homebrew.
echo ""
echo "Removing homebrew from Travis CI to avoid conflicts."
curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
chmod +x ~/uninstall_homebrew
~/uninstall_homebrew -fq
rm ~/uninstall_homebrew

# Install Miniconda.
if [ ! -f $HOME/miniconda/bin/activate ]; then
    echo ""
    echo "Installing a fresh version of Miniconda."
    rm -rf $HOME/miniconda
    curl -L https://repo.continuum.io/miniconda/$MINICONDA_FILE > ~/miniconda.sh
    bash ~/miniconda.sh -b -p ~/miniconda
    source ~/miniconda/bin/activate root
fi

# Reuse packages from the cache.
mv -n ~/miniconda/pkgs ~/cache/pkgs
rm -rf ~/miniconda/pkgs
ln -s ~/cache/pkgs ~/miniconda/pkgs

# Configure conda.
echo ""
echo "Configuring conda."
conda config --add channels conda-forge
conda config --add channels mcs07
conda config --set show_channel_urls true
conda install --yes --quiet conda-build-all
conda install --yes --quiet conda-forge-build-setup
source run_conda_forge_build_setup

# We just want to build all of the recipes.
conda build-all ./recipes --inspect-channels mcs07 --upload-channels mcs07 --matrix-condition "numpy >=1.11" "$PY_CONDITION" "r-base >=3.3.2"
