{% set name = "InChI" %}
{% set version = "1.05" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.inchi-trust.org/download/105/INCHI-1-SRC.zip
  sha256: 4ac311ca3a16fa75d695ec4fc711e74045c6d6c882dea0dd1055961fba643720
  patches:
    # downloaded package comes with no build scripts, need to
    # provide our own
    - SConstruct.patch

build:
  number: 4
  run_exports:
    - {{ pin_subpackage('inchi', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - scons

test:
  commands:
    - inchi-1
    - test -f $PREFIX/lib/libinchi.so  # [linux]
    - test -f $PREFIX/lib/libinchi.dylib  # [osx]
    - if not exist %LIBRARY_LIB%\inchi.lib exit 1  # [win]

about:
  home: https://www.inchi-trust.org/
  license: IUPAC/InChI-Trust Licence
  license_file: LICENCE
  summary: "InChI: open-source chemical structure representation algorithm"
  description: |
    Originally developed by the International Union of Pure and Applied  Chemistry (IUPAC),
    the IUPAC International Chemical Identifier (InChI) is a character string generated by
    computer algorithm. It is a tool to be used in software applications designed and
    developed by those who choose to use it.

    The InChI algorithm turns chemical structures into machine-readable strings of information.
    InChIs are unique to the compound they describe and can encode absolute stereochemistry
    making chemicals and chemistry machine-readable and discoverable. A simple analogy is that
    InChI is the bar-code for chemistry and chemical structures.

  doc_url: https://www.inchi-trust.org/oer/

extra:
  recipe-maintainers:
    - mcs07
