{% set name = "tesseract" %}
{% set version = "4.1.0rc1" %}
{% set sha256 = "d9795aab66fa2ef9134e1b50ea3c6c0849efc7fa08217e0161cfed5ac70fae1f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/tesseract-ocr/{{ name }}/archive/4.1.0-rc1.tar.gz
    sha256: {{ sha256 }}
    folder: tesseract
  - url: https://github.com/tesseract-ocr/tessdata_fast/archive/4.0.0.tar.gz
    sha256: f1b71e97f27bafffb6a730ee66fd9dc021afc38f318fdc80a464a84a519227fe
    folder: tessdata_fast

build:
  number: 1
  skip: True  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - pkg-config  # [not win]
    - cmake  # [win]
  host:
    - giflib  # [not win]
    - jpeg
    - leptonica
    - libpng
    - libtiff
    - libwebp
    - openjpeg
    - xz  # [not win]
    - zlib
  run:
    # libwebp doesn't have run_exports yet (on version in conda-forge-pinning)
    - libwebp

test:
  commands:
    - tesseract --help

about:
  home: https://github.com/tesseract-ocr/tesseract
  license: Apache-2.0
  license_family: Apache
  license_file: tesseract/LICENSE
  summary: Open Source OCR Engine
  doc_url: https://github.com/tesseract-ocr/tesseract
  dev_url: https://github.com/tesseract-ocr/tesseract

extra:
  recipe-maintainers:
    - mcs07
